### PR TITLE
Sanitize aws input command

### PR DESCRIPTION
**Pull request by CodingNagger**

### CODE REVIEW

**Comment by 69** [comment]
Not really a fix, still works with the following payloads:
```js
aws.command('test | touch HACKED');
aws.command('test; $(touch HACKED2)');
```

**Comment by CodingNagger** [comment]
Good point @69 ; I'll go and revise my copy but that'll require a slightly deeper insight into the available AWS commands to write something stricter. Thanks!

**Review by toufik-airane — APPROVED** [review]
LGTM.

**Comment by huntr-helper** [comment]
Sorry @CodingNagger, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request! We appreciate your effort and look forward to reviewing more of your fixes in the future! :hammer: :sunglasses:

**Pull request closed without merging**
